import { CategoryType, Supplier, PriceCategory } from './types';

export const APP_NAME = "Shivpriya Silk Mills";
export const AGENT_NAME = "Sajjan Poddar"; 
export const AGENT_CONTACT = "9825703224";
export const AGENT_EMAIL = "shivpriyasilkmills1008@gmail.com";

// Helper to assign random images based on category for visual appeal
const getImg = (cat: CategoryType, index: number) => {
  const sareeImgs = [
    'https://images.unsplash.com/photo-1610189012906-4783fdae2c26?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1609357606029-28f5858060f2?auto=format&fit=crop&q=80'
  ];
  const suitImgs = [
    'https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1564557287817-3785e38ec1f5?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1596783944749-e592751f7b88?auto=format&fit=crop&q=80'
  ];
  const materialImgs = [
    'https://images.unsplash.com/photo-1624912753874-80077f09171e?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1620799140408-ed5341cd2431?auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1520006403909-838d6b92c22e?auto=format&fit=crop&q=80'
  ];

  if (cat === CategoryType.SAREE) return sareeImgs[index % sareeImgs.length];
  if (cat === CategoryType.SUIT) return suitImgs[index % suitImgs.length];
  return materialImgs[index % materialImgs.length];
};

export const SUPPLIERS: Supplier[] = [
  // ================= SAREES =================
  {
    id: 'sar-1',
    name: "RAGHUPATI SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 1),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-2',
    name: "GANPATI EXCLUSIVE(PARI EXCLUSIVE)",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 2),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-3',
    name: "SHYAM VATIKA SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 3),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-4',
    name: "KHUSHBOO SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 4),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-5',
    name: "SHREE GANESH SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 5),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-6',
    name: "SHYAMHARI (MAHALAXMI FASHION)",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 6),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-7',
    name: "SHREE SIDDHIVINAYAK SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 7),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-8',
    name: "SONY SAREES",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 8),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-9',
    name: "RADHA KRISHNA PRINTS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 9),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-10',
    name: "M.J.TEXTILES",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 10),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-11',
    name: "OM FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 11),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-12',
    name: "SHREE SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 12),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-13',
    name: "RANI MAHARANI",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 13),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-14',
    name: "VAANI CREATION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 14),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-15',
    name: "D.C.SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 15),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-16',
    name: "MAA JAGDAMBA",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 16),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-17',
    name: "SANWARA SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 17),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-18',
    name: "J.R.K.FABRICS PVT.LTD.",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 18),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-19',
    name: "LAXMI SHRI FASHION",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 19),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-20',
    name: "MATA RANI FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 20),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-21',
    name: "RADHIKA SILK MILLS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 21),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-22',
    name: "KIRAN CREATION",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 22),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-23',
    name: "B.A. TEXTILE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 23),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-24',
    name: "SHREE SHYAM SILK MILLS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 24),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-25',
    name: "HARI OM FASHION",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 25),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-26',
    name: "ROOPALI",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 26),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-27',
    name: "PERFECT CHUNRI HOUSE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 27),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-28',
    name: "AMBAJI CREATION (DEV SAKHI)",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 28),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-29',
    name: "SHYAM PRIYA SAREE",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 29),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-30',
    name: "SAKHI SAREE",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 30),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-31',
    name: "PIYA BAWRI SAREES (429/B)",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 31),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-32',
    name: "LAXMI SYNTHETICS",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 32),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-33',
    name: "DURGA TEXTILE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 33),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-34',
    name: "SHREE BADE BABA INTENATIONAL",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 34),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-35',
    name: "RUPTARA CREATION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 35),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-36',
    name: "JAY DURGA FAB(panchwati)",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 36),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-37',
    name: "KEJRIWAL SILK MILL",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 37),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-38',
    name: "SAI PRAKASH SAREES",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 38),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-39',
    name: "RICHA SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 39),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-40',
    name: "SHAKTI ENTERPRISE (ankit)",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 40),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-41',
    name: "B.N.TEXTILE",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 41),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-42',
    name: "SATYAM PRINTS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 42),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-43',
    name: "SAKSHI FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 43),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-44',
    name: "R.MOHAN LAL & SONS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 44),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-45',
    name: "MRIDUL CREATION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 45),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-46',
    name: "VAISHNAVI SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 46),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-47',
    name: "MAAHI SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 47),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-48',
    name: "CHARU PRINTS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 48),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-49',
    name: "VAISHALI PRINTS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 49),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-50',
    name: "SUMANGALA SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 50),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-51',
    name: "SHYAM DIWANA SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 51),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-52',
    name: "SHREE MAHAVEER SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 52),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-53',
    name: "KAPIL CREATION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 53),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-54',
    name: "MAANVI FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 54),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-55',
    name: "SHYAMAK SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 55),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-56',
    name: "SHRI LADDU GOPAL",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 56),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-57',
    name: "HANUMAN SYNTHETICS",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 57),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-58',
    name: "SHREE SATI FASHION",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 58),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-59',
    name: "JANAK NANDINI PRINT",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 59),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-60',
    name: "JAY KRISHNA PRINTS",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 60),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-61',
    name: "SHREE SHYAM FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 61),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-62',
    name: "MAA KRIPA TRENDZ PVT.LTD.",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 62),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-63',
    name: "SARVESH SHAKTI PRINTS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 63),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-64',
    name: "ALOK RAJ FASHION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 64),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-65',
    name: "SUBHAANYA SAREES",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 65),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-66',
    name: "MANMAYI",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 66),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-67',
    name: "OMEGA DESIGNER",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 67),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-68',
    name: "AMBEY SYNTHETICS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 68),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-69',
    name: "SHUBHMILAN SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 69),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-70',
    name: "BHERU",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 70),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-71',
    name: "KAUSHAL SILK MILLS",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 71),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-72',
    name: "SACHIRUP SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 72),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-73',
    name: "KEJRIWAL SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 73),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-74',
    name: "SHRIWALI PRINTS",
    market: "M-2",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 74),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-75',
    name: "KESHAVPRIYA SAREES",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 75),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-76',
    name: "KODAS & COMPANY(top dyed banarasi)",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 76),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-77',
    name: "SHREE R.V. FASHION",
    market: "M-2",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 77),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-78',
    name: "V.S. SAREE HOUSE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 78),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-79',
    name: "ROOP REKHA SAREE",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 79),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-80',
    name: "AKASH LEELA FASHIONS",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 80),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-81',
    name: "ANUHARI PRINTS PVT.LTD.",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 81),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-82',
    name: "DHANLAXMI TEXTO FAB PVT.LTD.",
    market: "RAGHUKUL",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 82),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-83',
    name: "DINESH TEXTILES (DT)",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 83),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-84',
    name: "G 6 NX",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 84),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-85',
    name: "HARI PARI SAREE",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 85),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-86',
    name: "HIMANEE FASHIONS PVT LTD",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 86),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-87',
    name: "JASLEEN FASHION",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 87),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-88',
    name: "KAYAAN PRINTS PVT.LTD.",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 88),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-89',
    name: "LAXMI SHREE SAREE",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 89),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-90',
    name: "LOVELY LAXMI CREATION",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 90),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-91',
    name: "MAA SHAKAMBARI SILK MILLS",
    market: "RAGHUKUL",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 91),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-92',
    name: "MANBHAVAN SAREES",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 92),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-93',
    name: "MANGAL JYOTI SAREES",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 93),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-94',
    name: "MANPREET SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 94),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-95',
    name: "MISHRI CLOTHING",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 95),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-96',
    name: "N.S.SYNTHETICS PVT.LTD.",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 96),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-97',
    name: "NIRMALA SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 97),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-98',
    name: "PAATHSHAALA PRINTS",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 98),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-99',
    name: "PRASOON PRINTS PVT.LTD.",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 99),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-100',
    name: "ROHIT FASHION",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 100),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-101',
    name: "RONIX FASHION LLP",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 101),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-102',
    name: "SANCHHI SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 102),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-103',
    name: "SARVODAYA CREATIONS",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 103),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-104',
    name: "SATVACHAN SAREES",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 104),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-105',
    name: "SHAYRANA",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 105),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-106',
    name: "SHIV SHAKTI SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 106),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-107',
    name: "SHIVANSH FASHION",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 107),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-108',
    name: "SHREE GANESHKRUPA POLYCREATION PVT LTD",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 108),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-109',
    name: "SHREE LAXMINATH SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 109),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-110',
    name: "SHREE SIDDHI VINAYAK SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 110),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-111',
    name: "SHREENIKA SAREE",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 111),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-112',
    name: "SIDDHIMA SYNTHETICS",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 112),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-113',
    name: "SNEH MILAN SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 113),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-114',
    name: "SONU PRINTS",
    market: "RAGHUKUL",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 114),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-115',
    name: "SRISTI SAREES",
    market: "RAGHUKUL",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹1,000+'],
    priceRangeDisplay: "₹1,000+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 115),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-116',
    name: "SUKANYA FASHION",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 116),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-117',
    name: "VIHAANA PRINTS",
    market: "RAGHUKUL",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 117),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-118',
    name: "SUMEET FABRIC",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 118),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-119',
    name: "VASUKI CREATION",
    market: "RAGHUKUL",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 119),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-120',
    name: "AADYA SHAKTI SAREES",
    market: "KOHINOOR HOUSE",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 120),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-121',
    name: "ANKLESHWAR SILK MILLS PVT.LTD. ",
    market: "451 MARKET",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 121),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-122',
    name: "DIGAMBARI SAREE(LAXMI SYNTHETICS)",
    market: "KOHINOOR MKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 122),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-123',
    name: "DRESS GALLERY",
    market: "UDHNA UDHYOG NAGAR",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 123),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-124',
    name: "NAISHA SYNTHETICS",
    market: "REGENT",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 124),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-125',
    name: "JASBEER SYNTHETICS",
    market: "REGENT",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 125),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-126',
    name: "GOURIPATI CREATION",
    market: "MILLENIUM",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 126),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-127',
    name: "SHREE LAXMIKRUPA TEXTILE",
    market: "LK HOUSE",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 127),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-128',
    name: "LAXMI MATARANI TEXTILE",
    market: "SIDDHIVINAYAK HOUSE",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 128),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-129',
    name: "MADHUNADNAN TEXTILE",
    market: "SIDDHIVINAYAK HOUSE",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 129),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-130',
    name: "MAABHAWANI TRENDZ PVT LTD",
    market: "ANUPAM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 130),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-131',
    name: "MAHAVEER DESIGNER",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 131),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-132',
    name: "MAHIMA FASHION",
    market: "M-4",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 132),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-133',
    name: "MAN MANDIR FASHION",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 133),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-134',
    name: "POONAM CREATION",
    market: "ROHIT A/C ",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 134),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-135',
    name: "RAJESH KUMAR & SONS",
    market: "ANUPAM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 135),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-136',
    name: "RAVIRAJ TRADELINK ",
    market: "SILK HERITAGE",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 136),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-137',
    name: "S S FASHION",
    market: "M-4",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 137),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-138',
    name: "SAMBHAV STUDIO",
    market: "SURANA-101",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 138),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-139',
    name: "SHANTI PRINT(CP)",
    market: "KOHINOOR HOUSE",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 139),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-140',
    name: "SHIV TEX CREATION",
    market: "ANMOL",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 140),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-141',
    name: "SUAAMA FASHION",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 141),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-142',
    name: "SUCHITRA",
    market: "SILK PLAZA",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 142),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-143',
    name: "SUNAKSHI SAREE ",
    market: "REGENT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 143),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-144',
    name: "UNIVASTRA",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 144),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-145',
    name: "VIRAJ DESIGNER",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 145),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-146',
    name: "WOMANS HUB",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 146),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-147',
    name: "ANUSHTHAN",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 147),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-148',
    name: "GAURAV CREATION",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 148),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-149',
    name: "GUNJESHWARI",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 149),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-150',
    name: "GURUMATA DESIGNER(ANKLESHWAR)",
    market: "451 MARKET",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 150),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-151',
    name: "JAY AMBEY TEXTILE",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 151),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-152',
    name: "KRISHNA EMPORIUM",
    market: "KOHINOOR MKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 152),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-153',
    name: "LAXMIHARI",
    market: "SILK HERITAGE",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 153),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-154',
    name: "LAXMI RAMAN",
    market: "MILLENIUM",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 154),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-155',
    name: "LEELA FASHION",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 155),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-156',
    name: "MAHAKALI TEXTILE",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 156),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'sar-157',
    name: "MEENAXI PRINT",
    market: "M-4",
    specialty: "Print",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 157),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-158',
    name: "SHAHI LIBAS",
    market: "SILK HERITAGE",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 158),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-159',
    name: "PIKASHO",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 159),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'sar-160',
    name: "SAMPRIYA (PIKASHO)",
    market: "MILLENIUM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SAREE,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SAREE, 160),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },

  // ================= SUITS =================
  {
    id: 'suit-1',
    name: "A T S T FASHIONS",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 1),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-2',
    name: "AARADHYA SUITS",
    market: "AMBAJI",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 2),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-3',
    name: "TIRUPATI TEX FAB",
    market: "AMBAJI",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 3),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-4',
    name: "AMRIT FASHION",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 4),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-5',
    name: "AYUSHI FASHION",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 5),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-6',
    name: "AARTI FASHION(ANAND CREATION)",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 6),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-7',
    name: "ARCHI DESIGNER",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 7),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-8',
    name: "GANPATI CREATION (GC)",
    market: "NTM",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 8),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-9',
    name: "INNAYA",
    market: "NTM",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 9),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-10',
    name: "JAI HANUMAN CREATION",
    market: "RRTM",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 10),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-11',
    name: "GLOBAL SILK MILLS",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 11),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-12',
    name: "K BHARAT INTERNATIONAL",
    market: "RRTM",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 12),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-13',
    name: "K.M.FASHION",
    market: "RRTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 13),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-14',
    name: "KAMLA FASHION",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 14),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-15',
    name: "MD TEX",
    market: "ASHIRRWAD",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 15),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-16',
    name: "MAHI CREATION (MAYA COTTON)",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 16),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-17',
    name: "OM INTERNATIONAL",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 17),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-18',
    name: "PARTH FABTECH",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 18),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-19',
    name: "PAWAN CREATION",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹1,000+'],
    priceRangeDisplay: "₹1,000+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 19),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-20',
    name: "PRABHU KRUPA PRINT",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 20),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-21',
    name: "R.G.SYNTHETICS",
    market: "RRTM",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 21),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-22',
    name: "RIDDHIKA CREATION",
    market: "M-4",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 22),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-23',
    name: "NICKY TRADING CO.(VERNIKA)",
    market: "RRTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 23),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-24',
    name: "SHIVRAM TEXTILE",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 24),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-25',
    name: "SHREE BALAJI CREATION",
    market: "RRTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 25),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-26',
    name: "SHREENATH JI TEXTILE (SUNRISE)",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 26),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-27',
    name: "SUIT HOUSE",
    market: "INDIA MARKET",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 27),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-28',
    name: "VARJUN",
    market: "KUBER JI PARK",
    specialty: "Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 28),
    description: "Wholesale supplier dealing in Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-29',
    name: "VARSHNEY ALOK SUIT",
    market: "RKLP",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 29),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-30',
    name: "VIANNA TEX",
    market: "RKT",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 30),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-31',
    name: "VIVAAN FASHION",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 31),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-32',
    name: "KANAK FASHION",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 32),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-33',
    name: "KHATUPATI SYNTHETICS",
    market: "RKT",
    specialty: "Dyed, Print",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 33),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-34',
    name: "KING FABROTECH",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹1,000+'],
    priceRangeDisplay: "₹1,000+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 34),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-35',
    name: "MAHALAXMI FASHION",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 35),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-36',
    name: "POOJA SILK MILLS",
    market: "NTM",
    specialty: "Dyed, Print",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 36),
    description: "Wholesale supplier dealing in Dyed, Print fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-37',
    name: "RAGHUPATI POLYCOTS",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 37),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-38',
    name: "SATGURU SYNTHETICS",
    market: "NTM",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 38),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-39',
    name: "SHREE SHYAM FASHION",
    market: "RRTM",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 39),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-40',
    name: "SUMUKHI FASHION(READYMADE SUIT)",
    market: "RAJ TEXTILE TOWER",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 40),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-41',
    name: "SURYA FAB TEX",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹200+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 41),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-42',
    name: "VINAY TEXTILE",
    market: "RKT",
    specialty: "Dyed",
    isTopSupplier: true,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 42),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.8
  },
  {
    id: 'suit-43',
    name: "SHREE GOPAL CREATION",
    market: "M-2",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 43),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },
  {
    id: 'suit-44',
    name: "MAHASHYAM FAB(RANI SETHANI)",
    market: "JAY SHREE RAM MARKET",
    specialty: "Dyed",
    isTopSupplier: false,
    category: CategoryType.SUIT,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.SUIT, 44),
    description: "Wholesale supplier dealing in Dyed fabrics.",
    rating: 4.0
  },

  // ================= DRESS MATERIALS =================
  {
    id: 'mat-1',
    name: "GOVIND SILK MILLS",
    market: "HARI OM",
    specialty: "SHIRTING",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 1),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.8
  },
  {
    id: 'mat-2',
    name: "SHREE KRISHNA SHIRTING",
    market: "HARI OM",
    specialty: "SHIRTING",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 2),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.8
  },
  {
    id: 'mat-3',
    name: "KEDIA FAB",
    market: "SARVODAYA",
    specialty: "KURTA CLOTH",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 3),
    description: "Wholesale supplier dealing in KURTA CLOTH.",
    rating: 4.8
  },
  {
    id: 'mat-4',
    name: "ANCHAL SILK MILL",
    market: "NEW AADARSH",
    specialty: "MICRO",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 4),
    description: "Wholesale supplier dealing in MICRO.",
    rating: 4.8
  },
  {
    id: 'mat-5',
    name: "NIRANKARI",
    market: "SHREE KRISHNA HOUSE",
    specialty: "MICRO DYED+PRINT",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 5),
    description: "Wholesale supplier dealing in MICRO DYED+PRINT.",
    rating: 4.8
  },
  {
    id: 'mat-6',
    name: "POOJA FASHION",
    market: "RKT",
    specialty: "DRESS MATERIAL",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 6),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.0
  },
  {
    id: 'mat-7',
    name: "SAGARLENE",
    market: "ANUPAM",
    specialty: "SHIRTING",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 7),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.0
  },
  {
    id: 'mat-8',
    name: "MONDAY SHIRTING",
    market: "HARI OM",
    specialty: "SHIRTING",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 8),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.8
  },
  {
    id: 'mat-9',
    name: "SHREYA BOUTIK",
    market: "SHREE KUBER JI TEXTILE PARK",
    specialty: "DRESS MATERIAL",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 9),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.8
  },
  {
    id: 'mat-10',
    name: "SONIA FASHION",
    market: "RKT",
    specialty: "DRESS MATERIAL",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 10),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.8
  },
  {
    id: 'mat-11',
    name: "B.TEX FASHION",
    market: "RKT",
    specialty: "BROCKET",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 11),
    description: "Wholesale supplier dealing in BROCKET.",
    rating: 4.0
  },
  {
    id: 'mat-12',
    name: "JALAN FAB",
    market: "HARIHAR MARKET",
    specialty: "SHIRTING",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 12),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.8
  },
  {
    id: 'mat-13',
    name: "KRISHNA TEXTILE",
    market: "RKT",
    specialty: "DRESS MATERIAL",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 13),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.8
  },
  {
    id: 'mat-14',
    name: "LAXMINARAYAN TEXTILE",
    market: "RKT",
    specialty: "NET",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 14),
    description: "Wholesale supplier dealing in NET.",
    rating: 4.0
  },
  {
    id: 'mat-15',
    name: "KARISHMA FASHION",
    market: "RKT",
    specialty: "DRESS MATERIAL",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 15),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.0
  },
  {
    id: 'mat-16',
    name: "PRABHUKRUPA SYNTHETICS PVT LTD",
    market: "M-2",
    specialty: "LEHANGA",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 16),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.8
  },
  {
    id: 'mat-17',
    name: "SHEWANI SYNTHETICS",
    market: "RKT",
    specialty: "MICRO",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 17),
    description: "Wholesale supplier dealing in MICRO.",
    rating: 4.0
  },
  {
    id: 'mat-18',
    name: "SHYAMRAJ CREATION",
    market: "RAGHUKUL",
    specialty: "LEHANGA",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 18),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.8
  },
  {
    id: 'mat-19',
    name: "SIYONA TEX FAB",
    market: "M-2",
    specialty: "SHIRTING",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 19),
    description: "Wholesale supplier dealing in SHIRTING.",
    rating: 4.0
  },
  {
    id: 'mat-20',
    name: "SUNNY ENTERPRISE(CHETAN HARI)",
    market: "M-4",
    specialty: "READYMADE KURTA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 20),
    description: "Wholesale supplier dealing in READYMADE KURTA.",
    rating: 4.0
  },
  {
    id: 'mat-21',
    name: "SUR SHYAM FASHION",
    market: "ASHIRWAD",
    specialty: "LEHANGA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000'],
    priceRangeDisplay: "₹500 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 21),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.0
  },
  {
    id: 'mat-22',
    name: "WEDDING COLLECTION",
    market: "M-2",
    specialty: "LEHANGA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 22),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.0
  },
  {
    id: 'mat-23',
    name: "VD LEHANGA (CHETAN HARI)",
    market: "M-2",
    specialty: "LEHANGA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 23),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.0
  },
  {
    id: 'mat-24',
    name: "F TEX INDIA",
    market: "M-2",
    specialty: "DRESS MATERIAL",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 24),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.0
  },
  {
    id: 'mat-25',
    name: "RAKESH SILK MILLS",
    market: "M-2",
    specialty: "LEHANGA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 25),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.0
  },
  {
    id: 'mat-26',
    name: "NAVEEN PRINTS PVT.LTD.",
    market: "M-2",
    specialty: "WEDDING DUPATTA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 26),
    description: "Wholesale supplier dealing in WEDDING DUPATTA.",
    rating: 4.0
  },
  {
    id: 'mat-27',
    name: "TASVIR SAREES",
    market: "M-2",
    specialty: "LEHANGA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹500 - ₹1,000', '₹1,000+'],
    priceRangeDisplay: "₹500+",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 27),
    description: "Wholesale supplier dealing in LEHANGA.",
    rating: 4.0
  },
  {
    id: 'mat-28',
    name: "MATUSHREE PRINTS",
    market: "RAGHUKUL",
    specialty: "DRESS MATERIAL",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 28),
    description: "Wholesale supplier dealing in DRESS MATERIAL.",
    rating: 4.0
  },
  {
    id: 'mat-29',
    name: "SHREE JAGDAMBA TRADING CO.",
    market: "RAGHUKUL",
    specialty: "WEDDING DUPATTA",
    isTopSupplier: true,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500', '₹500 - ₹1,000'],
    priceRangeDisplay: "₹200 - ₹1,000",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 29),
    description: "Wholesale supplier dealing in WEDDING DUPATTA.",
    rating: 4.8
  },
  {
    id: 'mat-30',
    name: "SHREE BIHARIJI TEXTILE",
    market: "RRTM",
    specialty: "DUPATTA",
    isTopSupplier: false,
    category: CategoryType.DRESS_MATERIAL,
    priceCategories: ['₹200 - ₹500'],
    priceRangeDisplay: "₹200 - ₹500",
    location: "Surat, Gujarat",
    imageUrl: getImg(CategoryType.DRESS_MATERIAL, 30),
    description: "Wholesale supplier dealing in DUPATTA.",
    rating: 4.0
  }
];